# Generated by Django 5.1.5 on 2025-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='public_name',
            field=models.SlugField(blank=True, max_length=60),
        ),
    ]
