# Generated by Django 5.1.5 on 2025-01-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_public_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
