# Generated by Django 5.1.5 on 2025-01-31 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, default='profile_banners/default_banner.png', upload_to='profile_banners'),
        ),
    ]
